dist: trusty
language: python

before_install:
  - pip install -r requirements.txt
script:
  - export PYTHONPATH=$PWD:$PYTHONPATH
  - echo $PYTHONPATH
  - ls
  - python -c "import komodo;print(komodo.__file__);print(komodo.__version__)"
  - python -m komodo.lint examples/releases/unstable.yml examples/repository.yml
  - ./setup.py test
